# ----------------------------
# Makefile Options
# ----------------------------

NAME = invader
DESCRIPTION = "Ag C Toolchain Demo"
COMPRESSED = NO
LDHAS_ARG_PROCESSING = 0

BSSHEAP_LOW = 060000
BSSHEAP_HIGH = 09FFFF

CFLAGS = -Wall -Wextra -Oz 
CXXFLAGS = -Wall -Wextra -Oz 

#LOCAL_LIBS_SCRIPT = local_libs_script

# ----------------------------

include $(shell cedev-config --makefile)
