# ----------------------------
# Makefile Options
# ----------------------------

NAME = stdout
DESCRIPTION = "stdout"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
