# ----------------------------
# Makefile Options
# ----------------------------

NAME = helloworld
DESCRIPTION = "AgDev Hello World"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
