# ----------------------------
# Makefile Options
# ----------------------------

NAME = fileio
DESCRIPTION = "AgDev File I/O Demo"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
