# ----------------------------
# Makefile Options
# ----------------------------

NAME = ftoc
DESCRIPTION = "AgDev F to C Demo"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
