# ----------------------------
# Makefile Options
# ----------------------------

NAME = complex
DESCRIPTION = "Complex Numbers Demo"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
