# ----------------------------
# Makefile Options
# ----------------------------

NAME = fdiv
DESCRIPTION = "Float Division Demo"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
