# ----------------------------
# Makefile Options
# ----------------------------

NAME = printf
DESCRIPTION = "printf demo"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
