# ----------------------------
# Makefile Options
# ----------------------------

NAME = exit
DESCRIPTION = "AgDev exit example"
COMPRESSED = NO
LDHAS_ARG_PROCESSING = 0
LDHAS_EXIT_HANDLER = 1

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
