# ----------------------------
# Makefile Options
# ----------------------------

NAME = mos_time
DESCRIPTION = "Ag C Toolchain RTC Demo"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
