# ----------------------------
# Makefile Options
# ----------------------------

NAME = time
DESCRIPTION = "Time Demo"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
