# ----------------------------
# Makefile Options
# ----------------------------

NAME = float
DESCRIPTION = "Floats Demo"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
