# ----------------------------
# Makefile Options
# ----------------------------

NAME = stdin
DESCRIPTION = "Ag C Toolchain Demo"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
