# ----------------------------
# Makefile Options
# ----------------------------

NAME = stdio2
DESCRIPTION = "Ag C Toolchain Demo"
COMPRESSED = NO
LDHAS_ARG_PROCESSING = 0

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
