name: release

on:
  release:
    types: [created]

jobs:
  release_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run compile.sh
        run: |
          cd ..
          mkdir temp
          cd temp
          sudo sh ${{ github.workspace }}\compile.sh ${{ github.workspace }}
          
      - name: Zip (Linux)
        run: |
          cd ${{ github.workspace }}/../temp/AgDev_build
          (zip -r "$OLDPWD/AgDev_release_${{  github.ref_name }}_linux.zip")
          
      - name: Upload Linux ZIP to GitHub Release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ${{ github.workspace }}/../temp/AgDev_build/AgDev_release_${{  github.ref_name }}_linux.zip
          tags: true

  release_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run compile.bat
        run: |
          cd ..
          mkdir temp
          cd temp
          ${{ github.workspace }}\compile.bat ${{ github.workspace }}
          
      - name: Zip (Windows)
        run: |
          cd ${{ github.workspace }}\..\temp\AgDev_build
          powershell -Command "Compress-Archive * AgDev_release_${{  github.ref_name }}_windows.zip"
          dir

      - name: Upload Windows ZIP to GitHub Release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ${{ github.workspace }}\..\temp\AgDev_release_${{  github.ref_name }}_windows.zip
          tags: true
